PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX : <http://dbpedia.org/resource/>

SELECT ?person ?birth ?death WHERE {
	?person dbo:birthDate ?birth .
	?person rdf:type dbo:Athlete.
	?person dbo:birthPlace :Cuba .
FILTER (?birth < "1900-01-01"^^xsd:date) .
OPTIONAL{
	?person dbo:deathDate ?death .
	}
} LIMIT 100
