PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?item ?itemLabel ?twitter ?LinkedIN ?politieke_partij ?politieke_partijLabel ?positie_op_lijst WHERE {
  ?item p:P3602 ?node.
  ?item wdt:P551 wd:Q12892.
  OPTIONAL { ?item wdt:P2002 ?twitter. }
  OPTIONAL { ?item wdt:P2035 ?LinkedIN. }
  ?node ps:P3602 wd:Q16061881.
  OPTIONAL { ?node pq:P1545 ?positie_op_lijst. }
  OPTIONAL { ?node pq:P1268 ?politieke_partij. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],nl". }
}


predicados
p:P3602		http://www.wikidata.org/prop/:P3602
wdt:P551 	http://www.wikidata.org/prop/direct/:P551 
wdt:P2002	http://www.wikidata.org/prop/direct/:P2002
wdt:P2035	http://www.wikidata.org/prop/direct/:P2035
ps:P3602	http://www.wikidata.org/prop/statement/:P3602
pq:P1545	http://www.wikidata.org/prop/qualifier/:P1545
pq:P1268	http://www.wikidata.org/prop/qualifier/:P1268

IRI_ID = http://www.wikidata.org/prop/

objetos
wd:Q12892. 		http://www.wikidata.org/entity/Q12892
wd:Q16061881.	http://www.wikidata.org/entity/Q16061881

IRI_ID = http://www.wikidata.org/entity/